/*
CRIE UM DICIONÁRIO PARA ARMAZENAR OONTEÚDO DA BASE DE DADOS bdemail(ls.txt).
CRIE UM TIPO DE DADO PARA REPRESENTAR A LINHA DA BASE DE DADOS.
NO TIPO DE DADO, SELECIONE UM CAMPO PARA SER A CHAVE DO DICIONÁRIO.
APÓS O PREENCHIMENTO DO DICIONÁRIO, SOLICITE AO USUÁRIO UM VALOR DE EMAIL E
EXIBA O RESTANTE DOS DADOS ASSOCIADOS AO EMAIL. CONTINUE A INTERAGIR COM O
USUÁRIO ATÉ ELE FORNECER A PALAVRA FIM COMO VALOR DE EMAIL.
*/

#include "./taddic.h"

int main() {
  Dic emails = new_dic();
  return 0;
}